//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ayarlar
    {
        public int Id { get; set; }
        public string Kullanıcı_Adı { get; set; }
        public string Sifre { get; set; }
    }
}
