//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ödünç_Kitap_Verme
    {
        public int Id { get; set; }
        public string Üye_Adı { get; set; }
        public string Kitabın_Adı { get; set; }
        public Nullable<System.DateTime> Veriliş_Tarihi { get; set; }
        public string Kitabı_Veren { get; set; }
        public string Geri_Geldimi { get; set; }
        public Nullable<System.DateTime> Geliş_Tarihi { get; set; }
        public string Teslim_Alan { get; set; }
    }
}
