//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Üye_Ekleme
    {
        public int Id { get; set; }
        public string Tc { get; set; }
        public string İsim { get; set; }
        public string Soyisim { get; set; }
        public string Cinsiyet { get; set; }
        public string Dogum_Yeri { get; set; }
        public Nullable<System.DateTime> Dogum_Tarihi { get; set; }
        public string Cep_No { get; set; }
        public string Adres { get; set; }
        public string E_posta { get; set; }
        public string Eğitim { get; set; }
        public Nullable<System.DateTime> Üyelik_Tarihi { get; set; }
    }
}
